CREATE TABLE USERS(
 USER_ID NUMBER  NOT NULL ,
 CONSTRAINT USER_PK PRIMARY KEY(USER_ID),
 TYPE NVARCHAR2(20) NOT NULL ,
 EMAIL NVARCHAR2(20) NOT NULL,
 PASSWORD NVARCHAR2(20) NOT NULL,
 USER_NAME NVARCHAR2(10),
 PHONE NVARCHAR2(20),
 DATE_REGISTERED TIMESTAMP NOT NULL ,
 LAST_ACTIVE_DATE TIMESTAMP NOT NULL ,
 OFFICE_ID NUMBER,

 CONSTRAINT USERS_FK
 FOREIGN KEY (OFFICE_ID)
 REFERENCES OFFICES (OFFICE_ID)
);


CREATE SEQUENCE USERS_SEQ MINVALUE 1000 MAXVALUE 1000000000 START WITH 1001 INCREMENT BY 1;