CREATE TABLE USERS(
 USER_ID NUMBER  NOT NULL ,
 TYPE NVARCHAR2(20) NOT NULL ,
 EMAIL NVARCHAR2(20) NOT NULL,
 PASSWORD NVARCHAR2(20) NOT NULL,
 USER_NAME NVARCHAR2(10),
 PHONE NVARCHAR2(20),
 DATE_REGISTERED TIMESTAMP NOT NULL ,
 LAST_ACTIVE_DATE TIMESTAMP NOT NULL ,
 OFFICEID NUMBER NOT NULL,
 CONSTRAINT USER_PK PRIMARY KEY(USER_ID),
 CONSTRAINT OFFICEID_FK
 FOREIGN KEY (OFFICEID)
 REFERENCES OFFICES (OFFICE_ID) ON DELETE CASCADE
);


CREATE SEQUENCE USERS_SEQ MINVALUE 1000 MAXVALUE 1000000000 START WITH 1001 INCREMENT BY 1;