CREATE TABLE OFFICES
(
  OFFICE_ID NUMBER NOT NULL,
  CONSTRAINT OFFICE_PK PRIMARY KEY(OFFICE_ID),
  NAME NVARCHAR2(100) NOT NULL,
  ADDRESS NVARCHAR2(255),
  TEL NVARCHAR2(20),
  USERS_SET NUMBER,
  CONTACT NVARCHAR2(50) NOT NULL,
  
  CONSTRAINT OFFICE_FK
  FOREIGN KEY (USERS_SET)
  REFERENCES OFFICES(OFFICE_ID)

);

CREATE SEQUENCE OFFICEID_SEQ MINVALUE 1 MAXVALUE 10000000000 START WITH 1 INCREMENT BY 1;